# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "ios beta build"
  lane :beta do
    create_keychain(name: "apple-developer", password: "", default_keychain: true)
    import_certificate(keychain_name: "apple-developer", keychain_password: "", certificate_path: File.expand_path("~/certs/apple-developer.cer"), log_output: true)
    install_provisioning_profile(path: File.expand_path("~/profiles/profile.mobileprovision"))
    build_app
    deploygate
  end
end
