on:
  push:
    branches:
      - master
name: Auto Deploy to DeployGate
jobs:
  deploy:
    name: Auto Deploy
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@master
      - name: Extract Certificates and Provisioning Profile
        run: |
          mkdir ~/certs ~/profiles
          echo $APPLE_DEVELOPER_CERTIFICATE > ~/certs/apple-developer.cer
          echo $PROVISIONING_PROFILE > ~/profiles/profile.mobileprovision
        env:
          CERTIFICATE: ${{ secrets.APPLE_DEVELOPER_CERTIFICATE }}
          PROVISIONING_PROFILE: ${{ secrets.PROVISIONING_PROFILE }}
      - name: Pod install
        working-directory: ios
        run: pod install
      - name: Build app
        working-directory: ios
        run: fastlane beta
        env:
          DEPLOYGATE_API_TOKEN: ${{ secrets.DEPLOYGATE_API_TOKEN }}
